version: '1.1'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: myapp-server
    container_name: myapp-node-server
    # command: node server.js
    volumes:
      - ./backend/:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "4000:4000"
    env_file: ./backend/.env
    # environment:
    #   - NODE_ENV=development
    networks:
      - app-network
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: myapp-client
    container_name: myapp-react-client
    # command: npm start
    volumes:
      - ./frontend/:/usr/app
      - /usr/app/node_modules
    depends_on:
      - backend
    ports:
      - "80:80"
    env_file: ./frontend/.env
    networks:
      - app-network

networks:
    app-network:
        driver: bridge

volumes:
    data-volume:
    node_modules:
    web-root:
      driver: local