version: '1.1'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: express-server
    container_name: node-server
    # command: node server.js
    volumes:
      - ./backend/:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "4000:4000"
    env_file: ./backend/.env
    # environment:
    #   - NODE_ENV=development
    networks:
      - app-network
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: myapp-client-nginx
    container_name: nginx-react-client
    # command: npm start
    volumes:
      - ./frontend/:/usr/app
      - /usr/app/node_modules
      - /etc/letsencrypt/ssl/fullchain.pem:/etc/nginx/ssl/fullchain.pem
      - /etc/letsencrypt/ssl/privkey.pem:/etc/nginx/ssl/privkey.pem
      - ./frontend/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - backend
    ports:
      - "80:80"
      - "443:443"
    env_file: ./frontend/.env
    networks:
      - app-network
  # nginx:
  #   build:
  #     context: ./nginx
  #     dockerfile: Dockerfile
  #   image: nginx
  #   container_name: nginx-client-ssl
  #   ports:
  #     - "80:80"
  #   depends_on:
  #     - frontend
  #   volumes:

  #   networks:
  #     - app-network

networks:
    app-network:
        driver: bridge

volumes:
    data-volume:
    node_modules:
    web-root:
      driver: local